%clear all, close all, clc;

%for k = 2:9;
% k=2;
% l = 4; %1 ACLT_L, 2 ACLT_M, 3 CNTRL_L, 4 CNTRL_M %Muista vaihtaa nimi
% 

% Aja ensin Youngs_JM_IPN.m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% DEFINE
PathOfTheFolder = 'Inpit/SameTime/'; %Where you want the new inp to be written
inppi = 'SameTime_IPNDense.inp'; %Inp template
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Where those files are located:
cd /media/janne/Transcend/Janne/Tyot/Academic/PostDoc/Measurements/IPN/Models/Mallit/

nimi = name; %Name of the CSV file

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Korvataan aikaisempi mittauksesta riippunut aika vakiolla
% Comment if you want to use CSV derived values
strain_time = 10;
StepsForInp = [2700 2700 2700 2700 2700];
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%uusipaksuus = 0.743;
%vanhapaksuus = 0.496;

%
%paksuudet = xlsread('/home/jtmakela/Tyot/PhD/Mallit/Rabbit/Biomech/Paksuudet_1.xls');



% vanhapaksuus = paksuudet(i,4).*10^-3;
% uusipaksuus = paksuudet(i,5)*10^-3;

% Original thickness of the model in inp
vanhapaksuus = 1.5;
uusipaksuus = 1/10^4*fix(10^4*(h_plug));  %Pyöristetään jottei tule virhettä kun siirretään rustoa

%

steppi1 = 0.05*uusipaksuus; %KORJAA STEPPI NYT RIITTÄÄ YKS KUN EI MUUTU
%steppi2 = (vanhapaksuus-steppi1)*0.05+steppi1; %Eihän tätä tarvii ku
%amplitudeilla pelataan

%tiedostonimi = 'puristus_3D';
tiedostonimi = dir(inppi); %Tämän pohjalta tehdään muut

fid=fopen([tiedostonimi.name], 'r'); 
%temp=fread(fid, [1 inf]); % luetaan tiedosto

%ind = ind-1;

% fseek(fid,ind_start,-1);
% temprivi = fgetl(fid);
% luvut = sscanf(temp(ind_start:ind_end),'%f %c %f %c %f %c ');

temp = textscan(fid, '%s');


nodes_alku=find(ismember(temp{1},'*Node'))+1;
nodes_end=find(ismember(temp{1},'*Element,'))-1;
    

nodes = str2num(char(temp{1}(nodes_alku(1):nodes_end))); 


nodes = reshape(nodes,3,[])';
%increments = str2num(char(temp{1}(34:9:end-9))); 

% plot(nodes(:,2),nodes(:,3),'*');hold on;
% %plot(0,1.531,'r*');
% figure;
% plot(nodes(:,3),'*');

%

paksuus = nodes(end,3)-nodes(1,3);

% original suhteet = nodes(1:22:end,3)/paksuus; %CHECK IF YOU CHANGE MESH!!!!!!!!!!!!!!!!!!!!!
suhteet = nodes(1:62:end,3)/paksuus; %CHECK IF YOU CHANGE MESH!!!!!!!!!!!!!!!!!!!!!

uudetsuhteet = suhteet*uusipaksuus;


%kron(uudetsuhteet,ones(length(nodes)));
m2 = imresize(uudetsuhteet, [length(nodes) 1], 'nearest');

uudetnodet = [nodes(:,1) nodes(:,2) m2];

fclose all;

% plot(uudetnodet(:,2),uudetnodet(:,3),'*');hold on;
%

%
tiedostonimi = dir(inppi); %Tämän pohjalta tehdään muut

fid=fopen([tiedostonimi.name], 'r'); 
temp=fread(fid, [1 inf]); % luetaan tiedosto

ind_start = findstr('*Part, name=Cartilage', temp);
ind_end = findstr('*Element, type=CAX4P', temp);

ind2_start = findstr('*Instance, name=Cartilage, part=Cartilage', temp);
ind2_end = min(findstr('*End Instance', temp));

alku = findstr('** Job name: ', temp);
loppu = findstr('** Generated by: Abaqus/CAE 6.13-3', temp);

step_fid = findstr('*Amplitude, name=Amp-',temp); %Use only first 8
step_fid_end = findstr('** MATERIALS', temp);

step_starts = findstr('*Soils, consolidation, end=PERIOD, utol=1., cetol=1e+06', temp);
step_ends = findstr('** BOUNDARY CONDITIONS', temp);


amplitudi_alku = findstr('RP, 2, 2,', temp);
amplitudi_loppu = findstr('RP, 6, 6', temp);

fclose(fid);

%
summanoltava = 1.5;

printti = ['Removable=', num2str(StepsForInp(1)) ,'; Straintime=', num2str(strain_time),';;;']; %So that these are available in analyzis

%nimi = 'keke.txt';

%fid=fopen([tiedostonimi(2).name], 'w+'); 
fid=fopen([PathOfTheFolder, nimi(1:end-4) '.inp'], 'w+'); 
fprintf(fid, '%s', temp(1:alku-25)); %alkulöpinät
fprintf(fid, '%s\n', printti);
fprintf(fid, '%s%s%s\n', '** Job name: ', nimi, ' Model name: Model-1');
fprintf(fid, '%s', temp(loppu:ind_start-1)); %alkulöpinät


fprintf(fid, '%s\n', '*Part, name=Cartilage');
fprintf(fid, '%s\n', '*Node');

for i = 1:length(uudetnodet);
fprintf(fid, '%g%s%g%s%g\n', uudetnodet(i,1), ', ', uudetnodet(i,2), ', ', uudetnodet(i,3));
end

fprintf(fid, '%s', temp(ind_end:ind2_start-1)); 
fprintf(fid, '%s\n', '*Instance, name=Cartilage, part=Cartilage');
fprintf(fid, '%s%g%s\n', '0., ', summanoltava-uusipaksuus, ', 0.'); %Siirretään rusto kontaktiin


fprintf(fid, '%s', temp(ind2_end:step_fid(1)-1));


fprintf(fid, '%s\n', '*Amplitude, name=Amp-1');
fprintf(fid, '%s%g%s\n', '             0.,              0.,             ', strain_time, ',              1.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-2');
fprintf(fid, '%s%g%s\n', '             0.,              1.,           ',StepsForInp(2), ',              1.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-3');
fprintf(fid, '%s%g%s\n', '             0.,              1.,             ', strain_time, ',              2.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-4');
fprintf(fid, '%s%g%s\n', '             0.,              2.,           ',StepsForInp(3), ',              2.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-5');
fprintf(fid, '%s%g%s\n', '             0.,              2.,             ', strain_time, ',              3.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-6');
fprintf(fid, '%s%g%s\n', '             0.,              3.,           ',StepsForInp(4), ',              3.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-7');
fprintf(fid, '%s%g%s\n', '             0.,              3.,             ', strain_time, ',              4.');
fprintf(fid, '%s\n', '*Amplitude, name=Amp-8');
fprintf(fid, '%s%g%s\n', '             0.,              4.,           ',StepsForInp(5), ',              4.');
fprintf(fid, '%s\n', '**');
% 
% 
vali =55; %*Soils, consolidation, end=PERIOD, utol=1., cetol=1e+06 55 merkkiä

fprintf(fid, '%s', temp(step_fid_end:step_starts(1)+vali));

fprintf(fid, '%s%g%s\n', '0.5, ', strain_time,', 1e-05, 2, ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(2):amplitudi_alku(1)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

fprintf(fid, '%s', temp(amplitudi_loppu(2):step_starts(2)+vali));
fprintf(fid, '%s%g%s\n', '1., ', StepsForInp(2),', 1e-05, 100., ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(3):amplitudi_alku(2)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

%Steps 3&4
fprintf(fid, '%s', temp(amplitudi_loppu(3):step_starts(3)+vali));
fprintf(fid, '%s%g%s\n', '0.5, ', strain_time,', 1e-05, 2, ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(4):amplitudi_alku(3)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

fprintf(fid, '%s', temp(amplitudi_loppu(4):step_starts(4)+vali));
fprintf(fid, '%s%g%s\n', '1., ', StepsForInp(3),', 1e-05, 100., ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(5):amplitudi_alku(4)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

%Steps 5&6
fprintf(fid, '%s', temp(amplitudi_loppu(5):step_starts(5)+vali));
fprintf(fid, '%s%g%s\n', '0.5, ', strain_time,', 1e-05, 2, ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(6):amplitudi_alku(5)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

fprintf(fid, '%s', temp(amplitudi_loppu(6):step_starts(6)+vali));
fprintf(fid, '%s%g%s\n', '1., ', StepsForInp(4),', 1e-05, 100., ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(7):amplitudi_alku(6)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

%Steps 7%8
fprintf(fid, '%s', temp(amplitudi_loppu(7):step_starts(7)+vali));
fprintf(fid, '%s%g%s\n', '0.5, ', strain_time,', 1e-05, 2, ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(8):amplitudi_alku(7)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);

fprintf(fid, '%s', temp(amplitudi_loppu(8):step_starts(8)+vali));
fprintf(fid, '%s%g%s\n', '1., ', StepsForInp(5),', 1e-05, 100., ');
fprintf(fid, '%s\n', '**');
fprintf(fid, '%s', temp(step_ends(9):amplitudi_alku(8)-1));
fprintf(fid, '%s%g\n', 'RP, 2, 2, -', steppi1);



fprintf(fid, '%s', temp(amplitudi_loppu(9):end));




fclose(fid);



fclose all;

%end %FOR
